baseurl = "https://postsignull.github.io/"
title = "postsignull"
theme = "hugo-coder"
languagecode = "de"
defaultcontentlanguage = "de"

[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[caches]
[caches.images]
dir = ':cacheDir/images'

[markup.highlight]
style = "dracula"

[params]
author = "404｜M̶I̶N̶D̶_̶N̶O̶T̶_̶F̶O̶U̶N̶D̶"
avatarURL = "images/avatar.jpg"
license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>'
info = [""]

since = 2020

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

maxSeeAlsoItems = 10

customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[outputs]
home = ["HTML", "RSS"]

# Social links
[[params.social]]
name = "X"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 1
url = "https://x.com/postsignull/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 99
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

# Menu links
[[menu.main]]
name = "Beiträge"
weight = 1
url = "posts/"
[[menu.main]]
name = "Kategorien"
weight = 2
url = "categories/"
[[menu.main]]
name = "Über"
weight = 99
url = "pages/about/"
